name: commit
on:
  workflow_dispatch:

jobs:
  import:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit --allow-empty -m "Trigger workflow"
          git push

#      - name: Build docker image
#        run: docker build --no-cache -t pygithub .
#
#      - name: Run example
#        run: |
#          docker run --rm \
#            --env INPUT_REPO_TOKEN=${{ secrets.GITHUB_TOKEN }} \
#            pygithub src/teast.py