name: Verified Commit Workflow

on:
  workflow_dispatch:

jobs:
  verified_commit:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global commit.gpgSign false

      - name: Create Verified Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit --allow-empty -m "Trigger workflow"
          git push origin HEAD
